# This file was generated by GoReleaser. DO NOT EDIT.
cask "modern-ls" do
  version "1.0.6"

  on_macos do
    on_intel do
      sha256 "32a2f8464d955c2f479a80d0ca29fc7fd9be15040f327b1af866843b3c04988e"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "efb708cc015ab7c7394defb22021c14084010a433ef46d9d89d4566a028290ec"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b38076cf341f17e237207015bc8f8af1e46bd8ffc217b644b34733cd515b5261"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a79bda3dfd1d4525c7f002f16799b96bfc5fe6619c93985cc4034dce6c678129"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "modern-ls"
  desc "A beautiful, extremely fast, modern replacement for Unix ls."
  homepage "https://github.com/the-mayankjha/modern-ls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modern-ls"

  # No zap stanza required

end
