# This file was generated by GoReleaser. DO NOT EDIT.
cask "modern-ls" do
  version "1.0.10"

  on_macos do
    on_intel do
      sha256 "d58d9dc47391d1ddaeda9f0c86ed323a6c3576d313c8484024778ce1cc97f6b5"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f3b832568c7b914d2ae72bf8e3ea9c8abc162395bd0778245f88d81b7c27272"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57290e30d467f88a14f3d355bbed128f8695cda52acf75adde75c997e664e2b2"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e8be679d38a9a28155108bf748515bb843c66cad078f270d8db54bbb64e81d4"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "modern-ls"
  desc "A beautiful, extremely fast, modern replacement for Unix ls."
  homepage "https://github.com/the-mayankjha/modern-ls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modern-ls"

  # No zap stanza required

end
