# This file was generated by GoReleaser. DO NOT EDIT.
cask "modern-ls" do
  version "1.0.12"

  on_macos do
    on_intel do
      sha256 "2663d489c9dbe0ca2e93457bafedbfd3fd4b0d849b964fcc91ec7efc95bc9a05"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f555f5a0f68401f6397c9a063157d0bbd542e0db6fdcadbdfb39de5517fdd7a"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "56f927c55965db72094dbc5873253ffa8764c0aba8942ca29e9de8ad1565a09d"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4e98cea6a78ec72545e4241e73f54f1558a6b111cc768313000b278a0eb4d575"
      url "https://github.com/the-mayankjha/modern-ls/releases/download/v#{version}/modern-ls_#{version}_linux_arm64.tar.gz"
    end
  end

  name "modern-ls"
  desc "A beautiful, extremely fast, modern replacement for Unix ls."
  homepage "https://github.com/the-mayankjha/modern-ls"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modern-ls"

  # No zap stanza required

end
